//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Traverse channel. Without this, a client cannot reach subchannels, no matter which privileges he has there.
 **/
public interface PermissionTraverse
{
    int value = 2;
}
