//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Make new temporary channel as a subchannel of this channel.
 **/
public interface PermissionMakeTempChannel
{
    int value = 1024;
}
